source "http://rubygems.org"

# gem 'rubygems'
gem 'sinatra'

# require 'capture_stdout'
# require 'escape_utils'
gem 'slim'

gem 'haml'
gem 'compass'
gem 'aws-s3'
# require 'bootstrap-sass'

# gem 'eventmachine'
# gem 'happening'